# Generated by Django 2.2 on 2019-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/'),
        ),
    ]
